name: oneSafe
favicon: null
layout_spectrum: 0.3609923131298274
typography_spectrum: 0.3251836891286075
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#F7EDF0'
    - '#F4CBC6'
    - '#F4AFAB'
    - '#F4EEA9'
    - '#F4F482'
  brandStrength: 0.11577531509101391
  lightness: 0.5272521153092384
  saturation: 0.23285965668037534
  rhythmicContrast: 0.9989957334473729
purpose: []
